// <auto-generated />
using CompuRent.DiegoTest.Services.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CompuRent.DiegoTest.Services.DAL.Migrations
{
    [DbContext(typeof(MusicRadioIncDbContext))]
    [Migration("20210108021148_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CompuRent.DiegoTest.Models.Entities.AlbumSetEntity", b =>
                {
                    b.Property<int>("AlbumSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("AlbumSetId");

                    b.ToTable("album_sets");
                });

            modelBuilder.Entity("CompuRent.DiegoTest.Models.Entities.ClientEntity", b =>
                {
                    b.Property<string>("ClientId")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.HasKey("ClientId");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.ToTable("clients");
                });

            modelBuilder.Entity("CompuRent.DiegoTest.Models.Entities.PurchaseDetailEntity", b =>
                {
                    b.Property<int>("PurchaseDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumSetId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseDetailId");

                    b.HasIndex("AlbumSetId");

                    b.HasIndex("ClientId");

                    b.ToTable("purchase_details");
                });

            modelBuilder.Entity("CompuRent.DiegoTest.Models.Entities.SongSetEntity", b =>
                {
                    b.Property<int>("SongSetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AlbumSetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("SongSetId");

                    b.HasIndex("AlbumSetId");

                    b.ToTable("songs_sets");
                });

            modelBuilder.Entity("CompuRent.DiegoTest.Models.Entities.PurchaseDetailEntity", b =>
                {
                    b.HasOne("CompuRent.DiegoTest.Models.Entities.AlbumSetEntity", "AlbumSet")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("AlbumSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CompuRent.DiegoTest.Models.Entities.ClientEntity", "Client")
                        .WithMany("PurchaseDetails")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompuRent.DiegoTest.Models.Entities.SongSetEntity", b =>
                {
                    b.HasOne("CompuRent.DiegoTest.Models.Entities.AlbumSetEntity", "AlbumSet")
                        .WithMany("SongSets")
                        .HasForeignKey("AlbumSetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
